// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniServerProject.Infrastructure.Persistence;

#nullable disable

namespace MiniServerProject.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251218033726_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiniServerProject.Domain.Entities.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("UserId"));

                    b.Property<ulong>("Exp")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Gold")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("LastStaminaUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<short>("Stamina")
                        .HasColumnType("smallint");

                    b.HasKey("UserId");

                    b.HasIndex("Nickname");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
