// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniServerProject.Infrastructure.Persistence;

#nullable disable

namespace MiniServerProject.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251219131706_AddStageEnterLog")]
    partial class AddStageEnterLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiniServerProject.Domain.Entities.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("UserId"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentStageId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ulong>("Exp")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Gold")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("LastStaminaUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)1);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ushort>("Stamina")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("UserId");

                    b.HasIndex("Nickname");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MiniServerProject.Domain.Log.StageEnterLog", b =>
                {
                    b.Property<ulong>("StageEnterLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("StageEnterLogId"));

                    b.Property<DateTime>("EnteredDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("StageEnterLogId");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique();

                    b.ToTable("stage_enter_logs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
