// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniServerProject.Infrastructure.Persistence;

#nullable disable

namespace MiniServerProject.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiniServerProject.Domain.Entities.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("UserId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentStageId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ulong>("Exp")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Gold")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("LastStaminaUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)1);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ushort>("Stamina")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Nickname");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MiniServerProject.Domain.ServerLogs.StageClearLog", b =>
                {
                    b.Property<ulong>("StageClearLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("StageClearLogId"));

                    b.Property<ulong>("AfterExp")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("AfterGold")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("ClearedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GainExp")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GainGold")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RewardId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("StageClearLogId");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique();

                    b.ToTable("stage_clear_logs", (string)null);
                });

            modelBuilder.Entity("MiniServerProject.Domain.ServerLogs.StageEnterLog", b =>
                {
                    b.Property<ulong>("StageEnterLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("StageEnterLogId"));

                    b.Property<ushort>("AfterStamina")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("ConsumedStamina")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("EnteredDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("StageEnterLogId");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique();

                    b.ToTable("stage_enter_logs", (string)null);
                });

            modelBuilder.Entity("MiniServerProject.Domain.ServerLogs.StageGiveUpLog", b =>
                {
                    b.Property<ulong>("StageGiveUpLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("StageGiveUpLogId"));

                    b.Property<ushort>("AfterStamina")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("GaveUpDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("RefundStamina")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("StageGiveUpLogId");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique();

                    b.ToTable("stage_giveup_logs", (string)null);
                });

            modelBuilder.Entity("MiniServerProject.Domain.ServerLogs.UserCreateLog", b =>
                {
                    b.Property<ulong>("UserCreateLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("UserCreateLogId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("UserCreateLogId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_create_logs", (string)null);
                });

            modelBuilder.Entity("MiniServerProject.Domain.ServerLogs.UserCreateLog", b =>
                {
                    b.HasOne("MiniServerProject.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
